#pragma once
#include <JuceHeader.h>
#include <algorithm>
#include <cmath>
#include <vector>
#include "MonomachineChorusModel.h"

// CHORUS: a clone of the Monomachine FX-CHORUS machine, right after the filter (before RTRG).
// Built from MNM_CHORUS_PLAN.md (repo root). Every constant comes from MonomachineChorusModel.h,
// GENERATED by the MNMCHORUS companion project from black-box measurements of the real MnM OS
// running in an emulator -- see its FINDINGS (appendix of MNM_CHORUS_PLAN.md) for the "why".
// (Reference names stay out of the UI -- it's CHO / CHORUS there.)
//
// Per channel (all measured):
//   v  = clip(x * (INP/64)^2)                          input stage, hard clip
//   s  = 1/3 * sum of three linear-interpolated taps at C + A sin(theta + 2 pi k/3)
//        C = 15.02 + ceil(7.75 DEL) samples @ 44.1k, A = (C - 16) DEP/128,
//        theta = one sine LFO (runs backwards, starts at phase 0), R channel offset by WID
//   w  = clip((1 + k) v - k lp[t-1])                   written to the line; k ~ FB/127, so the
//                                                      tap sum feeds back with negative sign
//   lp = one-pole(s)                                   LP knob; feedback path only
//   y  = clip((128 - MIX)/128 v + MIX/254 s)
// Times are converted from the 44.1 kHz reference to the host rate (delay in ms, the one-pole
// pole mapped), so it runs at any sample rate; at 44.1k it is the measured machine.
//
// Knobs arrive as 0..1 and are quantised to the machine's 0..127 steps; each derived coefficient
// glides (~20 ms) so a knob move never clicks. Enabling fades in over 10 ms, disabling fades out
// over 20 ms and then leaves the buffer untouched (bit-exact) -- busy() says when. FB near 127
// rings for a very long time; the processor gives it an idle tail (wetPeak()). Live playback only,
// not baked into Save/Export, same as the other drawer FX. Header-only, plain doubles, no
// allocation after prepare() -- the smoke test drives exactly this code.
namespace r3wrk
{
struct MnmChorusEngine
{
    static constexpr int kMaxChannels = 2;
    static constexpr double kMaxDelayMs = 50.0;   // centre 22.7 ms + depth 22.1 ms, plus glide headroom

    struct Params
    {
        bool enabled = false;
        double del01 = 64 / 127.0, dep01 = 64 / 127.0, spd01 = 64 / 127.0, mix01 = 1.0,
               fb01 = 0.0, wid01 = 0.0, lp01 = 1.0, inp01 = 64 / 127.0;
    };

    static int raw127(double v01) noexcept { return juce::jlimit(0, 127, (int) std::lround(juce::jlimit(0.0, 1.0, v01) * 127.0)); }

    void prepare(double sampleRate, int numChannels)
    {
        sr = juce::jmax(8000.0, sampleRate);
        ratio = sr / mnmchorus::kRefRate;
        channels = juce::jlimit(1, kMaxChannels, numChannels);
        lineLen = (int) std::ceil(sr * kMaxDelayMs * 0.001) + 8;
        for (auto& ch : ch_)
            ch.line.assign((size_t) lineLen, 0.0f);
        glide = 1.0 - std::exp(-1.0 / (0.020 * sr));
        fadeInStep = 1.0 / (0.010 * sr);
        fadeOutStep = 1.0 / (0.020 * sr);
        reset();
    }

    // Clears the lines and loop filters, LFO back to its start phase, fade to 0.
    void reset() noexcept
    {
        for (auto& ch : ch_)
        {
            std::fill(ch.line.begin(), ch.line.end(), 0.0f);
            ch.lp = 0.0;
        }
        writePos = 0;
        phase = mnmchorus::kLfoStartPhase;
        fade = 0.0;
        lastPeak = 0.0f;
    }

    // Jump every glide straight to its target (offline tests / the enable edge).
    void snapToTargets(const Params& p) noexcept { cur = targetsFor(p); }

    bool busy() const noexcept { return fade > 0.0; }

    // Peak of the wet signal (s) over the last process() call -- the idle-tail silence detector.
    float wetPeak() const noexcept { return lastPeak; }

    // In place, numCh 1 or 2 (mono runs the L path only).
    void process(float* const* io, int numCh, int n, const Params& p) noexcept
    {
        lastPeak = 0.0f;
        if (! p.enabled && fade <= 0.0)
            return;   // fully bypassed -- the buffer is untouched
        numCh = juce::jmin(numCh, channels);
        const Coefs t = targetsFor(p);
        const double maxD = (double) lineLen - 3.0;
        constexpr double twoPi = juce::MathConstants<double>::twoPi;
        const double third = twoPi / 3.0;
        float peak = 0.0f;

        for (int i = 0; i < n; ++i)
        {
            cur.glideTo(t, glide);
            fade = p.enabled ? juce::jmin(1.0, fade + fadeInStep) : juce::jmax(0.0, fade - fadeOutStep);

            for (int c = 0; c < numCh; ++c)
            {
                auto& ch = ch_[c];
                const double th = twoPi * (phase + (c == 1 ? cur.widOff : 0.0));
                double s = 0.0;
                for (int k = 0; k < 3; ++k)
                {
                    const double d = juce::jlimit(1.0, maxD, cur.centre + cur.depth * std::sin(th + third * k));
                    s += readLinear(ch, d);
                }
                s *= (1.0 / 3.0);

                const double in = io[c][i];
                const double v = clip(in * cur.inGain, mnmchorus::kClipIn);
                const double w = clip((1.0 + cur.k) * v - cur.k * ch.lp, mnmchorus::kClipLine);   // lp: previous sample
                ch.lp = (1.0 - cur.a) * s + cur.a * ch.lp;
                ch.line[(size_t) writePos] = (float) w;

                const double y = clip(cur.dry * v + cur.wet * s, mnmchorus::kClipOut);
                io[c][i] = (float) (in + fade * (y - in));
                peak = juce::jmax(peak, (float) std::abs(s));
            }
            writePos = writePos + 1 == lineLen ? 0 : writePos + 1;
            if (! lfoFrozen)
            {
                phase += mnmchorus::kLfoDirection * cur.rate / sr;
                phase -= std::floor(phase);
            }
        }
        lastPeak = peak;

        // Self-heal: a non-finite value would otherwise live in the feedback loop forever.
        bool finite = std::isfinite(phase) && std::isfinite(cur.centre) && std::isfinite(cur.k);
        for (int c = 0; c < numCh; ++c)
            finite = finite && std::isfinite(ch_[c].lp);
        if (! finite)
        {
            const double f = fade;
            reset();
            snapToTargets(p);
            fade = f;
        }
    }

    // Test hooks.
    bool lfoFrozen = false;
    void setLfoPhase(double cycles) noexcept { phase = cycles - std::floor(cycles); }
    double lfoPhase() const noexcept { return phase; }
    // Current delay (host samples) of tap k on channel c.
    double tapDelaySamples(int c, int k) const noexcept
    {
        const double th = juce::MathConstants<double>::twoPi * (phase + (c == 1 ? cur.widOff : 0.0));
        return cur.centre + cur.depth * std::sin(th + juce::MathConstants<double>::twoPi / 3.0 * k);
    }

private:
    struct Coefs
    {
        double centre = 0, depth = 0, rate = 0, widOff = 0, k = 0, a = 0, inGain = 1, dry = 1, wet = 0;
        void glideTo(const Coefs& t, double g) noexcept
        {
            centre += g * (t.centre - centre); depth += g * (t.depth - depth);
            rate   += g * (t.rate - rate);     widOff += g * (t.widOff - widOff);
            k      += g * (t.k - k);           a      += g * (t.a - a);
            inGain += g * (t.inGain - inGain); dry    += g * (t.dry - dry);
            wet    += g * (t.wet - wet);
        }
    };

    Coefs targetsFor(const Params& p) const noexcept
    {
        using namespace mnmchorus;
        const int del = raw127(p.del01), dep = raw127(p.dep01), spd = raw127(p.spd01), mix = raw127(p.mix01),
                  fb = raw127(p.fb01), wid = raw127(p.wid01), lp = raw127(p.lp01), inp = raw127(p.inp01);
        Coefs t;
        t.centre = centreSamples44(del) * ratio;           // one extra host sample of loop delay is
        t.depth  = depthSamples44(del, dep) * ratio;       // inherent (lp from the previous sample)
        t.rate   = lfoRateHz(spd);
        t.widOff = widthOffsetCycles(wid);
        t.k      = loopGain(fb);
        t.a      = std::pow(loopPole44(lp), 1.0 / ratio);  // same cutoff at any host rate
        t.inGain = inputGain(inp);
        t.dry    = dryGain(mix);
        t.wet    = wetGain(mix);
        return t;
    }

    static double clip(double x, double c) noexcept { return x > c ? c : (x < -c ? -c : x); }

    struct Channel
    {
        std::vector<float> line;
        double lp = 0.0;
    };

    // Linear interpolation, `d` samples back from the next write slot (the slot this sample fills).
    double readLinear(const Channel& ch, double d) const noexcept
    {
        double pos = (double) writePos - d;
        if (pos < 0.0) pos += lineLen;
        const int i0 = (int) pos;
        const double f = pos - i0;
        const int i1 = i0 + 1 == lineLen ? 0 : i0 + 1;
        return (1.0 - f) * ch.line[(size_t) i0] + f * ch.line[(size_t) i1];
    }

    double sr = 44100.0, ratio = 1.0;
    int channels = 1, lineLen = 1, writePos = 0;
    Channel ch_[kMaxChannels];
    Coefs cur;
    double phase = 0.0, fade = 0.0, glide = 0.001, fadeInStep = 0.001, fadeOutStep = 0.001;
    float lastPeak = 0.0f;
};
}
