#pragma once
// GENERATED by MNMFILTER/mnmfilter/model.py  --  do not edit by hand.
// Empirical model of the Elektron Monomachine multimode filter (Base / Width /
// HP Q / LP Q), fitted from white-noise-through-filter recordings.
//   Source: ~/Documents/Claude/MNMFILTER   Runs: 867 Base x Width + 261 resonance.
//   Structure: 2-pole high-pass at Base, 2-pole low-pass at Base+Width (~11 dB/oct
//   measured), independent resonance per edge. Model vs measured: ~2.8 dB RMS
//   median across the Base x Width plane, ~6 dB with resonance engaged.
#include <cmath>
#include <array>

namespace r3wrk { namespace mnm {

// Knob values are 0..1 (they map to the MnM's 0..127 param range internally).

// HP -3 dB corner from the Base knob.  base01 == 0 => high-pass disengaged.
inline double hpCutoffHz (double base01) noexcept
{
    base01 = base01 < 0.0 ? 0.0 : (base01 > 1.0 ? 1.0 : base01);
    if (base01 < 0.012) return 0.0;                     // knob at bottom = no HP
    const double hz = std::pow (2.0, 16.22275 * base01 + 6.75282);
    return hz > 30000.0 ? 30000.0 : hz;
}

// LP -3 dB corner from Base + Width (Width is the passband gap above Base).
// Returns >= Nyquist-ish when the low-pass is effectively wide open.
inline double lpCutoffHz (double base01, double width01) noexcept
{
    base01  = base01  < 0.0 ? 0.0 : (base01  > 1.0 ? 1.0 : base01);
    width01 = width01 < 0.0 ? 0.0 : (width01 > 1.0 ? 1.0 : width01);
    double e = base01 + width01;
    if (e > 1.0) e = 1.0;
    return std::pow (2.0, 16.23477 * e + 5.79059);
}

// Q knob (0..1) -> biquad Q for that edge. Table from the resonance sweep;
// linear-interpolated. Both edges share this curve (HP Q and LP Q measured the
// same within noise). ~0.7 at 0, self-oscillation-ish by ~0.7.
inline double resonanceToQ (double q01) noexcept
{
    static const std::array<std::pair<double,double>, 6> T = {{ {0.0000, 0.7000}, {0.1575, 1.3780}, {0.3150, 4.5900}, {0.5039, 18.3370}, {0.7087, 35.0300}, {1.0000, 35.0300} }};
    q01 = q01 < 0.0 ? 0.0 : (q01 > 1.0 ? 1.0 : q01);
    for (size_t i = 1; i < T.size(); ++i)
        if (q01 <= T[i].first)
        {
            const double t = (q01 - T[i-1].first) / (T[i].first - T[i-1].first);
            return T[i-1].second + t * (T[i].second - T[i-1].second);
        }
    return T.back().second;
}

// True when the filter would change the sound (used to skip it otherwise).
inline bool engaged (double base01, double width01, double hpQ01, double lpQ01) noexcept
{
    return base01 >= 0.012 || (base01 + width01) < 0.985 || hpQ01 > 0.02 || lpQ01 > 0.02;
}

} } // namespace r3wrk::mnm
