#pragma once
// GENERATED by OTFILTER/otfilter/model.py  --  do not edit by hand.
// Empirical model of the Elektron Octatrack MKI FX1 multimode filter
// (Base / Width / Q), fitted from white-noise-through-filter recordings.
//   Source: ~/Documents/Claude/OTFILTER   ~324 Base x Width + Q captures.
//   Structure: 2-pole high-pass at Base, 2-pole low-pass at Base+Width,
//   one shared resonance (Q). The OT's real skirt is gentler (~8 dB/oct) than
//   the model's 12 dB/oct, which is the main residual.  Model vs measured:
//   ~3.8 dB RMS median in-band (323 pts).
#include <cmath>
#include <array>

namespace r3wrk { namespace ot {

// Knob values are 0..1; internally scaled to the OT's 0..127 param range and run
// through a fitted polynomial for log2(corner Hz). Coeffs are highest-power-first.

inline double evalPoly (const double* c, int n, double x) noexcept
{
    double y = 0.0;
    for (int i = 0; i < n; ++i) y = y * x + c[i];
    return y;
}

// HP -3 dB corner from the Base knob.  base01 == 0 => high-pass disengaged.
inline double hpCutoffHz (double base01) noexcept
{
    base01 = base01 < 0.0 ? 0.0 : (base01 > 1.0 ? 1.0 : base01);
    if (base01 < 0.012) return 0.0;                     // knob at bottom = no HP
    static const double C[] = { 0.089653374, 3.2899314 };
    const double hz = std::pow (2.0, evalPoly (C, (int)(sizeof(C)/sizeof(C[0])), base01 * 127.0));
    return hz > 30000.0 ? 30000.0 : hz;
}

// LP -3 dB corner from Base + Width (Width is the passband gap above Base), a
// quadratic in log2(fc). Returns >= Nyquist-ish when the low-pass is wide open.
inline double lpCutoffHz (double base01, double width01) noexcept
{
    base01  = base01  < 0.0 ? 0.0 : (base01  > 1.0 ? 1.0 : base01);
    width01 = width01 < 0.0 ? 0.0 : (width01 > 1.0 ? 1.0 : width01);
    double e = base01 + width01;
    if (e > 1.0) e = 1.0;
    static const double C[] = { 0.00024486962, 0.059263798, 2.9997923 };
    const double hz = std::pow (2.0, evalPoly (C, (int)(sizeof(C)/sizeof(C[0])), e * 127.0));
    return hz > 30000.0 ? 30000.0 : hz;
}

// Q knob (0..1) -> biquad Q. Single resonance on the OT, applied to both edges.
// Table from the resonance sweep; linear-interpolated. ~0.7 at 0.
inline double resonanceToQ (double q01) noexcept
{
    static const std::array<std::pair<double,double>, 6> T = {{ {0.0000, 0.7070}, {0.1575, 1.1280}, {0.3150, 1.7180}, {0.5039, 3.1820}, {0.7087, 6.1330}, {1.0000, 12.0590} }};
    q01 = q01 < 0.0 ? 0.0 : (q01 > 1.0 ? 1.0 : q01);
    for (size_t i = 1; i < T.size(); ++i)
        if (q01 <= T[i].first)
        {
            const double t = (q01 - T[i-1].first) / (T[i].first - T[i-1].first);
            return T[i-1].second + t * (T[i].second - T[i-1].second);
        }
    return T.back().second;
}

// True when the filter would change the sound (used to skip it otherwise).
inline bool engaged (double base01, double width01, double q01) noexcept
{
    return base01 >= 0.012 || (base01 + width01) < 0.985 || q01 > 0.02;
}

} } // namespace r3wrk::ot
